"""Add detailed fields to ContactMessage

Revision ID: 84fc6bf417ed
Revises: 9a126753ec09
Create Date: 2025-09-02 14:02:31.865838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84fc6bf417ed'
down_revision = '9a126753ec09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('province', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_message', schema=None) as batch_op:
        batch_op.drop_column('province')
        batch_op.drop_column('city')
        batch_op.drop_column('phone')
        batch_op.drop_column('last_name')

    # ### end Alembic commands ###
